### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by hdevalence** [gtank/ristretto255#25]
I don't know what the convention is in Go, since there aren't package files with semver strings, but: what's the status of this package? Should we tell people that it's considered stable? Is there a way to mark a "1.0 release"?

**Comment by hdevalence** [comment]
cc @gtank @FiloSottile

**Comment by FiloSottile** [comment]
If we make a v1.0.0 tag, we are committing to making no API breaking changes without bumping to `github.com/gtank/ristretto255/v2`. I'm not sure we've seen enough usage to make that step.

**Comment by hdevalence** [comment]
That's totally reasonable -- is there a way to signal that, beyond the possibility of breaking API changes, the package is mostly finished, and that people should try using it?

**Comment by FiloSottile** [comment]
We can make a v0.1.0 tag. That, along with good docs and no "don't use this" warnings, should do.

Want me to go ahead and make one?

**Comment by hdevalence** [comment]
That sounds great. Is there any doc work that needs doing before that happens? I'm happy to help, but I'd like to get this project over some arbitrarily-defined finish line :)

**Comment by FiloSottile** [comment]
Not that I can tell, I curated the godocs as we went along.

https://godoc.org/github.com/gtank/ristretto255

I'll make the tag.

**Comment by FiloSottile** [comment]
Done!
