### ISSUE TITLE
Fix build tags

### ISSUE THREAD

**Issue by gtank** [gtank/ristretto255#3]
Anything that relies on math/bits must not be built for Go versions that don't have that.

**Comment by gtank** [comment]
Covered in #13. When go1.12 lands, builds for `!amd64` or `noasm` should see a nice speed improvement.

**Comment by gtank** [comment]
There's still bits.UintSize in the big.Int conversion routines. This will need `go1.9`.

**Comment by FiloSottile** [comment]
Go 1.9 is long gone.

**Comment by gtank** [comment]
My friend the Go core developer :) Debian before buster still defaults to 1.7.
