### ISSUE TITLE
Improve variable-base scalar multiplication

### ISSUE THREAD

**Issue by gtank** [gtank/ristretto255#4]

**Comment by terryding77** [comment]
Hi, I tested ScalarMulti  with my code, and find there has too many temporary variables in **ExtendedGroupElement Add** and **Double** functions, so it takes huge memory(`10*5*uint64=400B` for Add func, `8*5*uint64=320B` for Double func) in Benchmark test and called GC. Maybe we can remove some temporary variables for improving performance.
![image](https://user-images.githubusercontent.com/11759109/51530564-383ce580-1e76-11e9-88f7-4c609e3f8307.png)
