### ISSUE TITLE
Decode error mismatch between Element and Scalar

### ISSUE THREAD

**Issue by tmthrgd** [gtank/ristretto255#40]
I've noticed a slight mismatch between the `Decode` methods for `Element` and for `Scalar`. For a wrong-length byte slice `Element.Decode` will return an error, but `Scalar.Decode` will panic. See https://play.golang.org/p/EcBWChvIIj_v.

It would be nice if `Scalar.Decode` (really `FromCanonicalBytes`) would also return an error instead of panicking.

**Comment by FiloSottile** [comment]
This would be addressed by #36.
